#Auther nmap
import re
# print(re.search('[0-9]{3}','abc32kl9863dkg3488gghhh'))
# print(re.search('[0-9]{1,3}','abc32kl9863dkg3488gghhh'))
# print(re.findall('[0-9]{1,3}','abc32kl9863dkg3488gghhh'))
# print(re.search('abc{2}','abc12345abccuyuabcabc'))
# print(re.search('(abc){2}','abc12345abccuyuabcabc'))
# print(re.search('abc|rts','abdyyrtsuu'))
# print(re.search('abc|rts','abcdyyrtsuu'))
# print(re.findall('abc|rts','abcdyyrtsuu'))
# print(re.search('(abc){2}a(456|564)c','abcabca456cdd'))
# print(re.search('(abc){2}\|','alexabcabc|'))
# print(re.search('(abc){2}(\||=){2}','alexabcabc|'))
# print(re.search('(abc){2}(\||=){2}','alexabcabc||'))
# print(re.search('(abc){2}(\||=){2}','alexabcabc|='))
# print(re.search('(abc){2}(\||=){2}','alexabcabc=='))
# print(re.search('(abc){2}(\||=){2}','alexabcabc=='))
# print(re.search('(abc){2}(\|\|=){2}','alexabcabc=='))
# print(re.search('(abc){2}(\|\|=){2}','alexabcabc||=||='))
# print(re.search('(abc){2}(\|\|=){2}','alexabcabc||='))
# print(re.search('(abc){2}(\|\|=){2}','alexabcabc||='))
# print(re.search('\A[0-9]+[a-z]\Z','A123a'))
# print(re.search('\A[0-9]+[a-z]\Z','1123a'))
# print(re.search('\s+','1ddd34ddds  \r\n- - +\r \na'))
# print(re.search('\s+','1ddd34ddds  \r    - - +\r \na   '))
# print(re.search('\s+','1ddd34ddds  \r\n- - +\r \na   '))
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656'))
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656').group())
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656').groupdict())
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656').group('id'))
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656').group(1))
# print(re.search('(?P<id>[0-9]+)','abc34eddf45656').group(1))
print(re.search('(?P<id>[0-9]+)(?P<name>[a-z]+)','abc34eddf45656'))
a=re.search('(?P<id>[0-9]+)(?P<name>[a-z]+)','abc34eddf45656').groupdict()
print(a['name'])
